version: '3.8'

services:
  # Mattermost Server
  mattermost-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mattermost-server-dev
    ports:
      - "8065:8065"
      - "8067:8067"
      - "8074:8074"
      - "8075:8075"
    volumes:
      - ./server/config:/mattermost/config
      - ./server/data:/mattermost/data
      - ./server/logs:/mattermost/logs
      - ./server/plugins:/mattermost/plugins
      - ./server/client/plugins:/mattermost/client/plugins
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SERVICESETTINGS_LISTENADDRESS=:8065
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10
      - MM_CACHESETTINGS_CACHETYPE=redis
      - MM_CACHESETTINGS_REDISADDRESS=redis:6379
      - MM_CACHESETTINGS_REDISPASSWORD=
      - MM_CACHESETTINGS_REDISDB=0
      - MM_CACHESETTINGS_REDISCACHEPREFIX=mattermost
      - MM_CACHESETTINGS_DISABLECLIENTCACHE=false
    depends_on:
      - postgres
      - redis
    networks:
      - mattermost-network

  # Mattermost Webapp
  mattermost-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
      args:
        MM_SERVICESETTINGS_SITEURL: http://localhost:8065
    container_name: mattermost-webapp-dev
    ports:
      - "8080:80"
    volumes:
      - ./webapp/channels/dist:/usr/share/nginx/html
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
    depends_on:
      - mattermost-server
    networks:
      - mattermost-network

  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    container_name: mattermost-postgres-dev
    environment:
      - POSTGRES_DB=mattermost_test
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mostest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mattermost-network

  # Redis Cache
  redis:
    image: redis:7.4.0
    container_name: mattermost-redis-dev
    ports:
      - "6379:6379"
    networks:
      - mattermost-network

volumes:
  postgres_data:

networks:
  mattermost-network:
    driver: bridge
