name: Opensearch Docker Image

on:
  push:
    branches:
      - master
    paths:
      - server/build/Dockerfile.opensearch
      - .github/workflows/build-opensearch-image.yml

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: opensearch/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: opensearch/docker-login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: opensearch/build-and-push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          provenance: false
          file: server/build/Dockerfile.opensearch
          push: true
          pull: true
          tags: mattermostdevelopment/mattermost-opensearch:2.7.0
          build-args: |
            OPENSEARCH_VERSION=2.7.0
